bedtools==2.31.1
biopython==1.83
blat==35
bowtie==1.3.1
gff3sort=0.1.*
gffread==0.12.7
igv==2.19.*
igvtools==2.17.3
matplotlib==3.8.4
matplotlib-base==3.8.4
mysql-connector-python==8.3.0
pandas==2.2.2
pyfaidx==0.8.1.1
python==3.10
repeatmasker==4.1.5
samtools==1.20
scikit-learn==1.4.2
tensorboard==2.14
tensorflow==2.14
trf==4.09.1
viennarna==2.6.4
